name: Run RSpec

on:
  push:
  pull_request:
    types:
      - ready_for_review

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get PRs for branch
        id: get_prs
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch: $BRANCH_NAME"

          PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository }}:$BRANCH_NAME")

          PR_NUMBER=$(echo "$PR_DATA" | jq -r '.[0].number')
          echo "PR Number: $PR_NUMBER"
          
          if [ "$PR_NUMBER" == "null" ]; then
            echo "No open PR found for this branch."
            echo "::set-output name=pr_found::false"
            exit 0
          fi
          
          IS_DRAFT=$(echo "$PR_DATA" | jq -r '.[0].draft')
          echo "Is Draft: $IS_DRAFT"

          if [ "$IS_DRAFT" == "true" ]; then
            echo "This PR is a draft. Exiting."
            echo "::set-output name=is_draft::true"
            exit 0
          else
            echo "This PR is not a draft. Continuing."
            echo "::set-output name=is_draft::false"
            echo "::set-output name=pr_found::true"
          fi

      - name: Continue only if not draft and PR found
        if: steps.get_prs.outputs.pr_found == 'true' && steps.get_prs.outputs.is_draft == 'false'
        run: echo "Goodbye World11111"

      - name: Continue only if not draft
        if: success() && steps.check_draft.outputs.is_draft != 'true'
        run: echo "Hello World22222"
