name: Run RSpec

on:
  release:
    types: [published]
  pull_request:
    types:
      - ready_for_review
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  echo:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello World"
      - name: Greeting
        run: echo "Goodbye World"

